# Dockerfile para el Patrón 4: Workspaces en overlay
FROM ros:humble

# Imagen base ligera sin modelos
# Los paquetes se añadirán en tiempo de despliegue usando Helm
CMD ["ros2", "launch", "app", "overlay_launch.py"]
